Update GET-Properties-Reference.md
Aaron-Gor/API-Docs pull request #11
Opened 2020-12-22 08:56 UTC by Aaron-Gor

@lsnovich Fixed #4

2020-12-25 10:02 UTC, lsnovich requested changes

2020-12-25 10:02 UTC, lsnovich commented on GET-Properties-Reference.md
>  ## EXAMPLE JSON CODING FOR GETTING THE BILL
```suggestion
## JSON Response Schema
```

2020-12-25 10:02 UTC, lsnovich commented on GET-Properties-Reference.md
>  }
```suggestion
```JSON
}
```

2020-12-25 10:02 UTC, lsnovich commented on GET-Properties-Reference.md
>  }
you also need 
the tick marks (```) at the end

2020-12-28 15:16 UTC, closed without merging

2020-12-28 15:16 UTC, Aaron-Gor commented
@lsnovich PR #11 closed as requested.